### ISSUE TITLE
Is this package is compatible with Laravel 5?

### ISSUE THREAD

**Issue by marlongichie** [codengine/laravel-custom-migrations#1]
Didn't see anything in the documentation, so just checking if this package is compatible with Laravel 5?

**Comment by codengine** [comment]
Hi, I haven't tested it yet with Laravel 5 but it shouldn't be a major problem. I'll test it next week.

**Comment by codengine** [comment]
Hey, sorry for the delay. I can assure that the package is Laravel 5 compatible. The current master and v1.1.* will support Laravel 5.

For Laravel 4 you can use the 1.0.* versions.
