### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by jorenvanhee** [codengine/laravel-custom-migrations#3]
Are you planning on offering Laravel 5.5 support?

The service providers are structured a little bit different there:
- ConsoleSupportServiceProvider registers the MigrationsServiceProvider
- ArtisanServiceProvider now contains the registerMigrateCommand etc methods

**Comment by codengine** [comment]
Hi,
currently I don't have any plans to adapt the source to Laravel 5.5, but feel free to send a PR if you like.

**Comment by jorenvanhee** [comment]
Alright, thanks for the quick reply.

I went with another approach for now, it might help someone.

I added a database connection for each tenant (platform): platform_1, platform_2... I put all the migrations for the platforms in a subfolder. Then I added a custom command `migrate-platforms` that does the following:

```php
<?php

$connections = collect(config('database.connections'))
    ->filter(function ($value, $key) {
        return preg_match("/platform_\d/", $key) === 1;
    })
    ->keys();

$connections->each(function ($connection) {
    $this->call('migrate', [
        '--path' => 'database/migrations/platform/',
        '--database' => $connection,
    ]);
});
```
